proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true

applications:
- name: AppleDemandPredictor
  route_prefix: /apples
  import_path: apple_predict:app
  runtime_env:
    working_dir: "https://github.com/ray-project/serve_config_examples/archive/36862c251615e258a58285934c7c41cffd1ee3b7.zip"
    pip:
    - mlflow==2.20.3
    - numpy==1.26.4
    - pandas==2.2.3
    - scikit-learn==1.2.2
    - scipy==1.11.4
    - xgboost==3.0.0
    env_vars:
      MLFLOW_TRACKING_URI: http://mlflow.mlnow.frenoid.com:30080/
      MLFLOW_TRACKING_USERNAME: mlflow
      MLFLOW_TRACKING_PASSWORD: mlflow
  deployments:
  - name: PredictApplesDemand
    num_replicas: 2
    ray_actor_options:
      num_cpus: 1.0